/*********************************************************************************************************************/
/*                                                  CODE GROUP                                                       */
/*********************************************************************************************************************/
/*                                               OBJECT SPECIFICATION                                                */
/*********************************************************************************************************************/
/*!
 * $Source: STM32F401_StartUp.c $
 * $Revision: Version 1.0 $
 * $Author: Carlos Martinez $
 * $Date: 2023-03-11
 */
/*********************************************************************************************************************/
/* DESCRIPTION :                                                                                                     */
/** STM32F401_StartUp.c
    Start up code file for microcontroller.
 */
/*********************************************************************************************************************/
/* NOTES :                                                                                                           */
/** 
 * In GNU C, you can use function attributes to declare certain things about functions called in your program which help 
 * the compiler optimize calls and check your code more carefully. For example, you can use attributes to declare that a 
 * function never returns (noreturn), returns a value depending only on its arguments (pure), or has printf-style arguments 
 * (format).
 * 
 * You can also use attributes to control memory placement, code generation options or call/return conventions within the 
 * function being annotated. Many of these attributes are target-specific. For example, many targets support attributes for 
 * defining interrupt handler functions, which typically must follow special register usage and return conventions.
 * 
 * Function attributes are introduced by the __attribute__ keyword on a declaration, followed by an attribute specification 
 * inside double parentheses. You can specify multiple attributes in a declaration by separating them by commas within the 
 * double parentheses or by immediately following an attribute declaration with another attribute declaration.
 * 
 * It has been found convenient to use __attribute_ _ to achieve a natural attachment of attributes to their corresponding 
 * declarations, whereas #pragma is of use for compatibility with other compilers or constructs that do not naturally form 
 * part of the grammar.
 * 
 * alias ("target")
 *  The alias attribute causes the declaration to be emitted as an alias for another symbol, which must be specified. 
 *  For instance, 
 *               void __f (); {  }
 *               void f () __attribute__ ((weak, alias ("__f")));
 *  defines ‘f’ to be a weak alias for ‘__f’. In C++, the mangled name for the target must be used. It is an error if ‘__f’ 
 *  is not defined in the same translation unit.
 *  This attribute requires assembler and object file support, and may not be available on all targets.
 * 
 * section ("section-name")
 *  Normally, the compiler places the code it generates in the text section. Some- times, however, you need additional sections, 
 *  or you need certain particular functions to appear in special sections. The section attribute specifies that a function lives 
 *  in a particular section. For example, the declaration:
 *      extern void foobar (void) __attribute__ ((section ("bar")));
 *  puts the function foobar in the bar section.
 *  Some file formats do not support arbitrary sections so the section attribute is not available on all platforms. If you need 
 *  to map the entire contents of a module to a particular section, consider using the facilities of the linker instead.
 * 
 * weak The weak attribute causes the declaration to be emitted as a weak symbol rather than a global. This is primarily useful 
 *  in defining library functions that can be overridden in user code, though it can also be used with non-function declarations. 
 *  Weak symbols are supported for ELF targets, and also for a.out targets when using the GNU assembler and linker.
 * 
 * naked This attribute allows the compiler to construct the requisite function declaration, while allowing the body of the 
 *  function to be assembly code. The specified function will not have prologue/epilogue sequences generated by the compiler. 
 *  Only basic asm statements can safely be included in naked functions
 */
/*********************************************************************************************************************/
/* ALL RIGHTS RESERVED                                                                                               */
/*                                                                                                                   */
/* The reproduction, transmission, or use of this document or its content is                                         */
/* not permitted without express written authority. Offenders will be liable                                         */
/* for damages.                                                                                                      */
/*********************************************************************************************************************/

/*                                                      Includes                                                     */
/*********************************************************************************************************************/
#include "STM32F401RE.h"
/*                                                Functions prototypes                                               */
/*********************************************************************************************************************/

/*                                                Constants and types                                                */
/*********************************************************************************************************************/

/*                                                 Exported Variables                                                */
/*********************************************************************************************************************/

/*                                              Function Implementation                                              */
/*********************************************************************************************************************/


/***************************************************Log Projects*******************************************************
 *|    ID   |  JIRA Ticket  |     Date    |                                Description                                |
 *| CMARTI  |  STM32F401-1  | 11-Mar-2023 | First version of STM32F401_StartUp.c                                      |
**********************************************************************************************************************/